services:
  scholarlyhub:
    build:
      context: .
      args:
        VITE_API_BASE_URL: "https://techhubschmanagement.onrender.com"
        VITE_TENANT_ID: "green"
      dockerfile: Dockerfile
    container_name: scholarlyhub
    restart: unless-stopped
    ports:
      - "3011:80"