// import type { SchoolApplication } from './types';

export const MOCK_APPLICATIONS = [
  {
    id: '1',
    name: 'Greenwood Academy',
    initials: 'GA',
    avatarColor: '#D84040',
    location: 'Victoria Island, Lagos, Nigeria',
    status: 'pending',
    submittedAt: 'Jul 27, 2026, 9:15 AM',
    email: 'admin@greenwoodacademy.edu.ng',
    phone: '+234 803 214 5567',
    country: 'Nigeria',
    state: 'Lagos',
    address: '14 Adeola Odeku Street, Victoria Island',
    branch: 'Main Campus',
    documents: [
      { id: 'd1', name: 'CAC Certificate of Registration.pdf', size: '812 KB', url: '#' },
      { id: 'd2', name: 'Proof of School Address.pdf',         size: '440 KB', url: '#' },
      { id: 'd3', name: 'Ministry of Education Approval.pdf',  size: '1.1 MB', url: '#' },
    ],
  },
  {
    id: '2',
    name: 'Sunrise International School',
    initials: 'SI',
    avatarColor: '#1E2D5A',
    location: 'East Legon, Greater Accra, Ghana',
    status: 'approved',
    submittedAt: 'Jul 24, 2026, 1:40 PM',
    email: 'office@sunriseintl.edu.gh',
    phone: '+233 24 552 8890',
    country: 'Ghana',
    state: 'Greater Accra',
    address: '22 Lagos Avenue, East Legon',
    approvedAt: 'Jul 25, 2026, 10:05 AM',
    documents: [
      { id: 'd4', name: 'Business Registration Certificate.pdf', size: '690 KB', url: '#' },
      { id: 'd5', name: 'School License.pdf',                    size: '980 KB', url: '#' },
    ],
  },
  {
    id: '3',
    name: 'Crestview High',
    initials: 'CH',
    avatarColor: '#2563EB',
    location: 'Westlands, Nairobi, Kenya',
    status: 'rejected',
    submittedAt: 'Jul 20, 2026, 8:05 AM',
    email: 'info@crestviewhigh.ac.ke',
    phone: '+254 712 334 007',
    country: 'Kenya',
    state: 'Nairobi',
    address: '9 Waiyaki Way, Westlands',
    branch: 'Westlands Branch',
    rejectedAt: 'Jul 21, 2026, 11:30 AM',
    rejectionReason:
      'The uploaded certificate of registration has expired. Please resubmit a valid, current CAC/registration certificate before we can proceed.',
    documents: [
      { id: 'd6', name: 'Certificate of Registration.pdf', size: '705 KB', url: '#' },
      { id: 'd7', name: 'Proof of Address.pdf',            size: '360 KB', url: '#' },
    ],
  },
  {
    id: '4',
    name: 'Bright Minds Academy',
    initials: 'BM',
    avatarColor: '#7C3AED',
    location: 'Gwarinpa, FCT, Nigeria',
    status: 'pending',
    submittedAt: 'Jul 26, 2026, 3:22 PM',
    email: 'admin@brightminds.edu.ng',
    phone: '+234 901 234 5678',
    country: 'Nigeria',
    state: 'FCT',
    address: '12 Gwarinpa Estate, Abuja',
    documents: [
      { id: 'd8', name: 'CAC Certificate.pdf',     size: '530 KB', url: '#' },
      { id: 'd9', name: 'School License.pdf',       size: '720 KB', url: '#' },
    ],
  },
  {
    id: '5',
    name: 'St. Augustine College',
    initials: 'SA',
    avatarColor: '#059669',
    location: 'Claremont, Western Cape, South Africa',
    status: 'pending',
    submittedAt: 'Jul 27, 2026, 7:48 AM',
    email: 'admin@staugustine.edu.za',
    phone: '+27 21 674 3300',
    country: 'South Africa',
    state: 'Western Cape',
    address: '5 Claremont Boulevard, Cape Town',
    documents: [
      { id: 'd10', name: 'Registration Certificate.pdf', size: '810 KB', url: '#' },
    ],
  },
  {
    id: '6',
    name: 'Kingfisher Secondary School',
    initials: 'KS',
    avatarColor: '#0891B2',
    location: 'GRA Phase 2, Rivers, Nigeria',
    status: 'pending',
    submittedAt: 'Jul 28, 2026, 11:10 AM',
    email: 'info@kingfisher.edu.ng',
    phone: '+234 803 456 7890',
    country: 'Nigeria',
    state: 'Rivers',
    address: '7 Aba Road, GRA Phase 2, Port Harcourt',
    documents: [
      { id: 'd11', name: 'CAC Document.pdf',         size: '640 KB', url: '#' },
      { id: 'd12', name: 'Ministry Approval.pdf',    size: '890 KB', url: '#' },
    ],
  },
  {
    id: '7',
    name: 'Riverdale Montessori',
    initials: 'RM',
    avatarColor: '#EA580C',
    location: 'Lekki Phase 1, Lagos, Nigeria',
    status: 'pending',
    submittedAt: 'Jul 28, 2026, 2:33 PM',
    email: 'hello@riverdalemontessori.ng',
    phone: '+234 812 345 6789',
    country: 'Nigeria',
    state: 'Lagos',
    address: '3A Admiralty Way, Lekki Phase 1',
    documents: [
      { id: 'd13', name: 'Registration Certificate.pdf', size: '475 KB', url: '#' },
      { id: 'd14', name: 'Tax Clearance.pdf',            size: '320 KB', url: '#' },
    ],
  },
];
